name: dartdoc
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: A documentation generator for Dart.
homepage: https://github.com/dart-lang/dartdoc
dependencies:
  analyzer: any
  args: any
  grinder: '>=0.6.0 <0.7.0'
  intl: any
  logging: any
  mustache4dart:
    git:
      url: https://github.com/sethladd/mustache4dart.git
      ref: lambda-with-context
  path: any
  yaml: any
  markdown: any
  html5lib: any
dev_dependencies:
  http: any
  unittest: any
executables:
  dartdoc: null
